### PR TITLE
V5 partner content

### PR DESCRIPTION
**Pull request by notlee**
**⚠️ ready for review but do not merge:** some coordination is required to 
remove ads and globe trotter overrides

### Replace paid post labels with partner content styles.

The commercial design team created new teaser designs to replace
"paid posts" with "partner content". The ads team worked with
the commercial design team to refine requirements and rollout
the new design to ft.com with overrides:
https://github.com/Financial-Times/n-native-ads/blob/0fa02c2a685085e9a3e183672569431670eb260a/main.scss

However neither the product design team or Origami were 
involved and so the design strikes out from other teasers.
E.g. the "partner content" label no longer looks like a label
but differs from tags in that it is not a link and is uppercase.

This commit brings the overrides into Origami to:
- make maintence easier
- reduce css bundle size
- roll the changes out everywhere, including the app
- update demos and document the change, so we have a
solid base for future updates by the product design team

Some limited changes have been made from the ads overrides:
- the hover state isn't oxford, its inline with other teasers
- the "by [company name]" prefix is darker, to pass WCAG 2.0
contrast guidelines and meet DAC accreditation

These updates must be released to v4 and v5, as key pages on
ft.com is one major behind the app.

### Correct date markup in demos and readme.

- only some demos show the live timestamp
- demos use the `o-teaser__timestamp-date` class correctly
- the readme uses the `o-teaser__timestamp-date` class correctly,
and also mentions the use of `o-date`

### Screenshots

ordered, before/after

Screenshot 2020-09-14 at 14 25 16
Screenshot 2020-09-14 at 14 25 22
Screenshot 2020-09-14 at 14 25 25
Screenshot 2020-09-14 at 14 25 26
Screenshot 2020-09-14 at 14 25 33
Screenshot 2020-09-14 at 14 25 35
Screenshot 2020-09-14 at 14 25 39
Screenshot 2020-09-14 at 14 25 42

### CODE REVIEW

**Review by chee — APPROVED** [review]
this looks really good!

also: oh no!

**Comment by notlee** [comment]
thanks @chee! 

fyi. I just did a force push to update some pa11y demo markup

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.1.5 to 5e4508958f6caf0bd1db42a4dbbdf25060925bf6
css: 0.76kb decrease (-0.05kb/gzip)

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.1.5 to 803f0a02f926e63c099e1c9a950a5fa010b0f379
css: 0.76kb decrease (-0.05kb/gzip)

**Review by chee — APPROVED** [review]
i am 1000% sure i fixed that readme warning last week. sorry it's happening

**Comment by notlee** [comment]
no worries! looks like the demos including a msuatch variable `is-live` which is not actually set. I'm going to run Percy to check all our demos are as expected here

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.1.5 to 2630d472a0289e8f71c32aeff8dc291df935a1d8
css: 0.76kb decrease (-0.05kb/gzip)

**Comment by origamiserviceuser** [comment]
👋 Percy has finished running the visual regression testing!

**Comment by notlee** [comment]
oh we have exceeded our percy limit :(

**Comment by notlee** [comment]
A comparison of all demos before/after
comparison-before-after

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.1.5 to 82ddcc7a0d789decab80600d6d9b6b0adfb6d369
css: 0.76kb decrease (-0.05kb/gzip)

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.1.5 to d2536b095e7db1700980b167abfe3e8c7179b71e
css: 0.8kb decrease (-0.05kb/gzip)

**Comment by chee** [comment]
i can't tell if all of this section of changes is as expected

image


and also this slightly more ensquishened box:

image

**Comment by notlee** [comment]
that's expected :) The first is the pa11y demo which has all the things -- and now a more representive use of the live variant. The second is because the markup was wrong in the demo so we had double margin! Fortunately Customer Products are smart cookies and haven't copied this mistake (yet)

**Review by JakeChampion — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
👋 Percy has finished running the visual regression testing!

**Comment by JakeChampion** [comment]
@notlee I ran the Percy job and it has found some visual changes -- https://percy.io/Financial-Times/o-teaser/builds/7029119 -- I assume the same ones that you saw when you took the screenshots of every demo earlier in this thread

**Comment by origamiserviceuser** [comment]
:tada: This PR is included in version v5.2.0 :tada:

**Pull request merged**
