### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.0.1 to 65d278140080248672dd071989205b67569f8636
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.0.1 to 583c02a75a50af2ee2917a9f5ba304be6aa92390
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.0.1 to c5bd9c2f47eeab20e3b001f35bcb5053ac7b3e1b
No significant bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 5.0.1 to f691801e4427d820fcda1b9f2772b76746f1fe19
No significant bundle size differences found.

**Pull request merged**
