### PR TITLE
prevent overflow

### PR DESCRIPTION
**Pull request by chivchila**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 3.5.6 to 5ee40003feab39ddfa9f1eea5cee42b68726a0c1
No significant bundle size differences found.

**Comment by chivchila** [comment]
before
Screenshot 2019-10-14 at 14 54 12
after
Screenshot 2019-10-14 at 14 53 37

**Comment by notlee** [comment]
Thanks @chivchila! Breaking a word instead of overflowing seems reasonable to me. Your change applies to Hero teasers only but this would be equally useful for other teasers. Would you mind moving this to the `oTeaserElementsDefault` mixin? 
https://github.com/Financial-Times/o-teaser/blob/9165397573bb51416b87efac2844b5f99e4dfa2a/src/scss/_mixins.scss#L47

**Comment by notlee** [comment]
Since our chat I've realised that using flexbox rather than an inline display is great here, in addition to the `break-word` update. Here's a demo using a video teaser:

**With this word-break update:**
Screenshot 2019-10-14 at 15 12 48

**With this word-break update + flexbox:**
Any extra space is ignored by flex and the spans are wrapped.
```css
.o-teaser__meta {
    display: flex;
    flex-wrap: wrap;
}
```
Screenshot 2019-10-14 at 15 13 01

What do you think @i-like-robots?

(relates to https://github.com/Financial-Times/x-dash/pull/403#issuecomment-541108824)

**Comment by i-like-robots** [comment]
This value doesn't appear to be supported by Edge or IE11, though that may not be a blocker as I'm not aware that we've had this issue reported on FT.com.

https://caniuse.com/#feat=mdn-css_properties_word-break_break-word

**Review by notlee — APPROVED** [review]
Olga opened a [separate PR](https://github.com/Financial-Times/o-teaser/pull/138/files) which builds on this. It applies the break to all teaser headings and uses flexbox so whitespace is ignored and tags, which would fit within the width of the teaser, wrap rather than overflow or break when combined with a prefix. However, extra markup in the x-dash implementation means that can't be released yet, so we'll release this to fix to resolve the specific overflow issue identified in the app

**Pull request merged**
