### PR TITLE
Breaking

### PR DESCRIPTION
**Pull request by notlee**
See https://github.com/Financial-Times/o-teaser/issues/134 and https://github.com/Financial-Times/o-teaser/issues/140

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 3.5.9 to edddadd9999712eb74cb0b8c190112751c9fe2ce
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 3.5.9 to 5eb7e9c04a58fe4c895318bd4e9cda390a322702
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 3.5.9 to 8e7037afb9ba895234a74f1e32b38a68cb136d1c
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 3.5.9 to 69842c9179c00fb00ce08c4c9ab922e67ad68a53
No significant bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 3.5.9 to 819bc8c98cd5192717a99180530fabd102769236
css: 0.36kb decrease (-0.03kb/gzip)

**Review by rowanmanning — APPROVED** [review]
Gave this one last look over, I think it's ready to ship. 00:30 on a Friday? yolo

**Comment by rowanmanning** [comment]
Ugh all of FT.com's nightly jobs are running, so inconsiderate of them

**Comment by origamiserviceuser** [comment]
o-teaser bundle size difference from 3.5.9 to e2911e640c06c5cf64d9e1adc45502499b9b3408
css: 1.41kb increase (0.13kb/gzip)

**Pull request merged**
